#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate docs/drivers/coverage.md from the device profiles.

A coverage matrix that is maintained by hand is a coverage matrix that is wrong, and wrong in
the direction that matters: it claims support for a channel a profile stopped mapping. So this
reads the TOML profiles -- the same files the firmware's register tables are generated from --
and renders what they actually declare.

  python3 tools/gen_coverage.py            regenerate
  python3 tools/gen_coverage.py --check    fail if the committed file is stale

tools/check_layering.sh runs --check, the same way it already guards the EverSolar fixtures.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import gen_profiles

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "drivers" / "coverage.md"

# The channels worth a column, in the order a person reads them. Deliberately NOT every canonical
# id: a matrix wide enough to include every battery rail is a matrix nobody scans.
COLUMNS: list[tuple[str, str]] = [
    ("AC W", "ac.power.total"),
    ("AC V", "ac.phase_l1.voltage"),
    ("AC A", "ac.phase_l1.current"),
    ("Hz", "ac.frequency"),
    ("PV W", "dc.power.total"),
    ("PV1 V/A", "dc.mppt_1.voltage"),
    ("PV2 V/A", "dc.mppt_2.voltage"),
    ("E day", "energy.today"),
    ("E tot", "energy.total"),
    ("Temp", "inverter.temperature"),
    ("Bat %", "battery.soc"),
    ("Bat W", "battery.power"),
    ("Bat V", "battery.voltage"),
    ("Bat °C", "battery.temperature"),
    ("Load W", "load.power"),
]


def load_profiles() -> list[dict]:
    vocabulary = gen_profiles.load_vocabulary()
    commands = gen_profiles.load_command_vocabulary()
    enum_enumerators = gen_profiles.load_enum_command_names()
    enum_commands = {n for n, e in commands.items() if e in enum_enumerators}
    paths = sorted(
        p
        for p in gen_profiles.PROFILES_DIR.rglob("*.toml")
        if not p.name.startswith("_")
    )
    return [
        gen_profiles.parse_profile(p, vocabulary, commands, enum_commands)
        for p in paths
    ]


def render(profiles: list[dict]) -> str:
    profiles = sorted(profiles, key=lambda p: (p["manufacturer"].lower(), p["id"]))
    out: list[str] = []
    w = out.append

    w("# Device coverage")
    w("")
    w(
        "**Generated by `tools/gen_coverage.py` from the profiles in `profiles/`. Do not edit by"
    )
    w(
        "hand** — run the tool instead. `tools/check_layering.sh` fails if this file is stale."
    )
    w("")
    w(
        "What a tick means: the profile maps that channel, so the firmware publishes it when the"
    )
    w(
        "device answers. It does **not** mean anybody has seen it against real hardware — see"
    )
    w(
        "[Verification](#verification). The **Status** column is that second question, answered"
    )
    w(
        "per profile: it is the map's own `status`, declared in its TOML, and never inherited"
    )
    w(
        "from the driver that reads it. One driver serves every table here, so promoting the"
    )
    w("driver must not promote a map nobody has confirmed.")
    w("")

    w("## Read coverage")
    w("")
    w("| Profile | Vendor | Status | " + " | ".join(c[0] for c in COLUMNS) + " |")
    w("|---|---|---|" + "---|" * len(COLUMNS))
    for p in profiles:
        mapped = {r["measurement"] for r in p["registers"]}
        cells = ["✔" if mid in mapped else "·" for _, mid in COLUMNS]
        # How far the MAP is proven, read straight from the profile. Column count and ticks say
        # how much a profile claims; this column says how much of that claim has been tested.
        w(
            f"| `{p['id']}` | {p['manufacturer']} | {p['status']} | "
            + " | ".join(cells)
            + " |"
        )
    w("")
    w(
        "`·` means the profile does not map it. That is usually deliberate and always explained in"
    )
    w(
        "the profile's own comments — see [Why a channel is missing](#why-a-channel-is-missing)."
    )
    w("")

    w("## Write coverage")
    w("")
    w("| Profile | Setpoint | Register | Dispatchable | Verified |")
    w("|---|---|---|---|---|")
    any_writes = False
    for p in profiles:
        for wr in p["writes"]:
            any_writes = True
            words, _ = gen_profiles.TYPES[wr["type"]]
            # writeFor() serves a single-register FC06 row and nothing else.
            servable = words == 1 and wr["function"] == "write_single"
            reason = "yes" if servable else "no — needs FC16"
            w(
                f"| `{p['id']}` | `{wr['command']}` | holding {wr['address']} | "
                f"{reason} | {'yes' if wr['verified'] else '**no**'} |"
            )
    if not any_writes:
        w("| — | — | — | — | — |")
    w("")
    w(
        "**Nothing in this table can move an inverter today.** A row reaches the bus only when"
    )
    w(
        "`Verified` is yes *and* `Dispatchable` is yes, and no profile sets the first. See"
    )
    w(
        "[write-path.md](../device-profiles/write-path.md) for what the path can and cannot do."
    )
    w("")

    w("## Verification")
    w("")
    w("| Profile | Sources | Cross-checked | Hardware |")
    w("|---|---|---|---|")
    for p in profiles:
        w(f"| `{p['id']}` | see profile header | see profile header | **no** |")
    w("")
    w(
        "Every profile in this tree is transcribed from documentation or from implementations"
    )
    w(
        "running on somebody else's hardware. **None has been confirmed against the device it"
    )
    w(
        "describes by this project.** The per-profile header says exactly what it rests on: a"
    )
    w(
        "vendor specification, two independent implementations that agree, or one implementation."
    )
    w("")
    w(
        "If you own one of these inverters, the bring-up checklist in its protocol document is the"
    )
    w(
        "thing to run — and reporting that a map turned out *wrong* is as useful as reporting that"
    )
    w("it worked.")
    w("")

    w("## Why a channel is missing")
    w("")
    w("The gaps are not oversights, and they cluster into a handful of causes:")
    w("")
    w(
        "- **The sources disagree, or are silent.** Battery power is the recurring case: it is"
    )
    w(
        "  mapped for exactly one profile, because that is the only one whose documentation states"
    )
    w(
        "  which direction positive means. A confidently inverted battery graph is worse than an"
    )
    w("  absent one.")
    w(
        "- **It needs arithmetic.** A profile maps one register to one channel. A value that has to"
    )
    w(
        "  be combined with a direction register, or split into two rails, or summed from several"
    )
    w("  registers, cannot be expressed.")
    w(
        "- **The vocabulary has no id for it.** House-load power is carried by several profiles'"
    )
    w("  sources and agreed by them; there is no canonical id yet, so it is blocked on")
    w(
        "  [the vocabulary](../device-profiles/canonical-measurements.md) rather than on a register."
    )
    w(
        "- **Only one source has it.** A channel one implementation carries and another does not is"
    )
    w("  usually right for a model the profile may not be describing.")
    w("")
    w(
        "Each profile's own comments name the reason for its own gaps, in the file, next to the"
    )
    w("rows that surround them.")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    content = render(load_profiles())
    check_only = "--check" in argv
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
    if check_only:
        if current != content:
            sys.stderr.write(
                "docs/drivers/coverage.md is stale; run python3 tools/gen_coverage.py\n"
            )
            return 1
        print(f"coverage matrix: OK ({OUTPUT.relative_to(ROOT)})")
        return 0
    if current != content:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
